### ISSUE TITLE
Panic in stacktrace mapping

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-data#326]
```
{"log.level":"error","@timestamp":"2024-07-22T15:24:51.682+0100","log.logger":"request","log.origin":{"function":"github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1","file.name":"middleware/log_middleware.go","file.line":59},"message":"internal error","service.name":"apm-server","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"Go-http-client/1.1","source.address":"127.0.0.1","http.request.id":"a390e2cf-1bbc-4485-9251-4f082c5b2cbe","event.duration":449042,"http.request.body.bytes":4096,"http.response.status_code":500,"error.message":"internal error: runtime error: invalid memory address or nil pointer dereference","error.stack_trace":"goroutine 180 [running]:
	runtime/debug.Stack()
		runtime/debug/stack.go:24 +0x64
	github.com/elastic/apm-server/internal/beater/api.apmMiddleware.RecoverPanicMiddleware.func2.1.1()
		github.com/elastic/apm-server/internal/beater/middleware/recover_panic_middleware.go:55 +0x134
	panic({0x106a3dd20?, 0x108025640?})
		runtime/panic.go:770 +0x124
	github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/v2.mapToStracktraceModel({0x1400f88a008?, 0x1a, 0x140028c2120?}, {0x14018f18f00, 0x1a, 0x140198f5ada?})
		github.com/elastic/apm-data@v1.9.0/input/elasticapm/internal/modeldecoder/v2/decoder.go:1320 +0x80
	github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/v2.mapToSpanModel(0x140115ec608, 0x1401860dce0)
		github.com/elastic/apm-data@v1.9.0/input/elasticapm/internal/modeldecoder/v2/decoder.go:1282 +0x13f0
	github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/v2.DecodeNestedSpan({0x106d5b2e0, 0x14018c351e0}, 0x140000bceb8, 0x14018c62c18)
		github.com/elastic/apm-data@v1.9.0/input/elasticapm/internal/modeldecoder/v2/decoder.go:218 +0x118
	github.com/elastic/apm-data/input/elasticapm.(*Processor).readBatch(0x1400062ea50, {0x1082a85b8?, 0x50?}, 0x14018f80580, 0x14018c114a0?, 0x14018c62c18, 0x14018c351e0, 0x14018bff380)
		github.com/elastic/apm-data@v1.9.0/input/elasticapm/processor.go:206 +0x1d8
	github.com/elastic/apm-data/input/elasticapm.(*Processor).handleStream(0x1400062ea50, {0x106d69418, 0x14018c0b470}, 0x14018c62c18, 0x0?, 0x0?, 0x0?, {0x106d54668, 0x140004001c8}, 0x14018bff380)
		github.com/elastic/apm-data@v1.9.0/input/elasticapm/processor.go:310 +0x4c
	github.com/elastic/apm-data/input/elasticapm.(*Processor).HandleStream(0x1400062ea50, {0x106d69418?, 0x14018c0b470?}, 0x14018f80580, {0x10f2ef308, 0x14018c11400}, 0xa, {0x106d54668, 0x140004001c8}, 0x14018bff380)
		github.com/elastic/apm-data@v1.9.0/input/elasticapm/processor.go:291 +0x480
	github.com/elastic/apm-server/internal/beater/api.(*routeBuilder).backendIntakeHandler.Handler.func2(0x14014b97c80)
		github.com/elastic/apm-server/internal/beater/api/intake/handler.go:77 +0x158
	github.com/elastic/apm-server/internal/beater/api.backendMiddleware.AnonymousRateLimitMiddleware.func3.1(0x14018bf6d80?)
		github.com/elastic/apm-server/internal/beater/middleware/rate_limit_middleware.go:49 +0xc4
	github.com/elastic/apm-server/internal/beater/api.backendMiddleware.AuthMiddleware.func2.1(0x14014b97c80)
		github.com/elastic/apm-server/internal/beater/middleware/auth_middleware.go:70 +0x1ac
	github.com/elastic/apm-server/internal/beater/api.backendMiddleware.ResponseHeadersMiddleware.func1.1(0x14014b97c80)
		github.com/elastic/apm-server/internal/beater/middleware/response_headers_middleware.go:33 +0xa4
	github.com/elastic/apm-server/internal/beater/middleware.MonitoringMiddleware.(*monitoringMiddleware).Middleware.func1.1(0x14014b97c80)
		github.com/elastic/apm-server/internal/beater/middleware/monitoring_middleware.go:53 +0xac
	github.com/elastic/apm-server/internal/beater/api.apmMiddleware.RecoverPanicMiddleware.func2.1(0x106923ce0?)
		github.com/elastic/apm-server/internal/beater/middleware/recover_panic_middleware.go:60 +0x50
	github.com/elastic/apm-server/internal/beater/middleware.TimeoutMiddleware.func1.1(0x14014b97c80)
		github.com/elastic/apm-server/internal/beater/middleware/timeout_middleware.go:35 +0x3c
	github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1(0x14014b97c80)
		github.com/elastic/apm-server/internal/beater/middleware/log_middleware.go:47 +0xa0
	github.com/elastic/apm-server/internal/beater/api.NewMux.(*ContextPool).HTTPHandler.func11({0x106d633d0, 0x14013e417a0}, 0x14018bf6d80)
		github.com/elastic/apm-server/internal/beater/request/context_pool.go:47 +0xe0
	net/http.HandlerFunc.ServeHTTP(0x14018bf6d80?, {0x106d633d0?, 0x14013e417a0?}, 0x14018bf6d80?)
		net/http/server.go:2166 +0x38
	go.elastic.co/apm/module/apmhttp/v2.(*handler).ServeHTTP(0x14018bf6c60?, {0x106d633d0?, 0x14013e417a0?}, 0x1082a85b8?)
		go.elastic.co/apm/module/apmhttp/v2@v2.6.0/handler.go:74 +0xac
	github.com/gorilla/mux.(*Router).ServeHTTP(0x140005ce240, {0x106d633d0, 0x14013e417a0}, 0x14018bf6b40)
		github.com/gorilla/mux@v1.8.1/mux.go:212 +0x194
	github.com/elastic/gmux.ConfigureServer.(*mux).withGRPCInsecure.func3({0x106d633d0?, 0x14013e417a0?}, 0x0?)
		github.com/elastic/gmux@v0.3.2/mux.go:119 +0x120
	net/http.HandlerFunc.ServeHTTP(0x10?, {0x106d633d0?, 0x14013e417a0?}, 0x14013e417a0?)
		net/http/server.go:2166 +0x38
	net/http.serverHandler.ServeHTTP({0x106d5ec28?}, {0x106d633d0?, 0x14013e417a0?}, 0x6?)
		net/http/server.go:3137 +0xbc
	net/http.(*conn).serve(0x14002bf2090, {0x106d69418, 0x1400028f3e0})
		net/http/server.go:2039 +0x508
	created by net/http.(*Server).Serve in goroutine 169
		net/http/server.go:3285 +0x3f0
	","ecs.version":"1.6.0"}
```

**Comment by lahsivjar** [comment]
The root cause of this is that the `Reslice` function ([ref](https://github.com/elastic/apm-data/blob/cee5ac3fc5f2ee66f156133992882cae758e2b66/input/elasticapm/internal/modeldecoder/modeldecoderutil/slice.go#L23-L44)) in APM data falsely assumes that the whole capacity of the slice is non-nil.
